- hosts: webservers
  become: yes
  tasks:
  - name: Install httpd package
    yum:
      name: httpd
      state: latest
  - name: Enable and start httpd service
    service:
       name: httpd
       state: started
       enabled: yes
  - name: Create index.html file for hosting static content
    copy:
      content: "Hoorraaayyy!!! My first playbook ran successfully \n"
      dest: /var/www/html/index.html
  - name: open the firewall port for the http service 
    firewalld:
      service: http
      permanent: yes
      state: enabled
      immediate: yes
