---
- name: Install webserver and firewall
  hosts: webservers
  become: true
  vars:
    rule: http
  tasks:
    - name: Include the variables from the YAML file
      ansible.builtin.include_vars: vars/variables.yml

    - name: Include the environment file and set the variables
      ansible.builtin.import_tasks: tasks/environment.yml
      vars:
        package: httpd
        service: httpd
        svc_state: started

    - name: Install the firewall
      ansible.builtin.dnf:
        name: "{{ firewall_pkg }}"
        state: present

    - name: Start the firewall
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Open the port for {{ rule }}
      ansible.posix.firewalld:
        service: "{{ rule }}"
        immediate: true
        permanent: true
        state: enabled

    - name: Create index.html
      ansible.builtin.copy:
        content: "{{ ansible_fqdn }} has been customized using Ansible on the {{ ansible_date_time.date }}\n"
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '644'
