- name: Install Apache and starts the service
  hosts: webservers
  become: true
  tasks:
    - name: Install the required package
      ansible.builtin.dnf:
        name: "{{ ansible_local.custom.general.package }}"
        state: present

    - name: Start the service
      ansible.builtin.service:
        name: "{{ ansible_local.custom.general.service }}"
        state: "{{ ansible_local.custom.general.state }}"
