- name: Install Apache and start the service
  hosts: webservers
  become: true
  vars:
    web_pkg: httpd
    firewall_pkg: firewalld
    web_service: httpd
    firewall_service: firewalld
    rule: http
  tasks:
    - name: Install the required packages
      ansible.builtin.dnf:
        name:
          - '{{ web_pkg }}'
          - "{{ firewall_pkg }}"
        state: present
    - name: Start and enable the service {{ firewall_service }}
      ansible.builtin.service:
        name: "{{ firewall_service }}"
        enabled: true
        state: started

    - name: Start and enable the service {{ web_service }}
      ansible.builtin.service:
        name: "{{ web_service }}"
        enabled: true
        state: started
    - name: Create web content to be served
      ansible.builtin.copy:
        content: "Example web content"
        dest: /var/www/html/index.html
        mode: '0644'

    - name: Open the port for {{ rule }}
      ansible.posix.firewalld:
        service: "{{ rule }}"
        permanent: true
        immediate: true
        state: enabled
