- name: Verify the Apache service
  hosts: localhost
  tasks:
    - name: Ensure the webserver is reachable
      ansible.builtin.uri:
        url: http://server1.example.com
        status_code: 200
