- name: Install the package {{ package }}
  ansible.builtin.dnf:
    name: "{{ package }}"
    state: present
- name: Start the service {{ service }}
  ansible.builtin.service:
    name: "{{ service }}"
    state: "{{ svc_state }}"
