version: '3'
services:
  master:
    image: ubuntu:latest
    container_name: ansible_master
    tty: true
    volumes:
      - ./master:/etc/ansible
    networks:
      - ansible-net
    command: /bin/bash

  slave1:
    image: ubuntu:latest
    container_name: ansible_slave1
    tty: true
    networks:
      - ansible-net
    command: /bin/bash

  slave2:
    image: ubuntu:latest
    container_name: ansible_slave2
    tty: true
    networks:
      - ansible-net
    command: /bin/bash

networks:
  ansible-net:
    driver: bridge
