name: ansible-lint
on:
  push:
    branches: ["main", "release/v*"]
  pull_request:
    branches: ['main', 'release/v*']
jobs:
  ansible-Lint:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
      - name: Check code out from github and into "ubuntu-latest" (or our environment)
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core

      - name: Install Ansible Galaxy Collections
        run: |
          ansible-galaxy collection install ansible.posix
          sleep 10

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
